### ISSUE TITLE
Layout in CSS

### ISSUE THREAD

**Issue by FatimaZelay** [halima98/the-client-website#7]
De layout van je homepage ziet er super goed uit en komt overeen met je figma design. Probeer alle elementen te centreren, de button werkend te maken.

**Comment by MarsGotBars** [comment]
## review Marcin
- allereerst zou ik geen br gebruiken *buiten* een p tag, binnen-in is wel toegestaan.
  - gebruik voor de spacing gewoon een margin-top, dan kun je ze ook spacen zoals je zelf wilt
```css
p + p{
  margin-top: 1rem;
}
```
- fix je font import link eventjes;
```css
@font-face {
    font-family: 'Figtree';
    src: url('../assets/fonts/Figtree-VariableFont_wght.ttf') format('truetype'); /* deze moet 2 puntjes hebben voor de /assets */
    font-weight: 400;
    font-style: normal;
}
```
